name: 'acero_analysis'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'acero_analysis'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  acero_analysis:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
      +schema: marts

# Configuring seeds
seeds:
  acero_analysis:
    +column_types:
      id: "int64"
      created_at: "timestamp"

# Configuring snapshots
snapshots:
  acero_analysis:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Configuring tests
tests:
  +warn_if: ">100"
  +error_if: ">1000"

# Configuring documentation
docs-paths: ["docs"]

# Configuring packages
packages-install-path: "dbt_packages"

# Configuring vars
vars:
  # Add any variables you want to use in your models here
  start_date: "2019-01-01"
  end_date: "2024-01-01"
